REQUEST_SUMMARIZE_ONTOLOGY = "summarize"

ONTOLOGY_CHATBOT_DISPATCHER = "start-work"
ONTOLOGY_DISPATCHER_FETCHER = "fetch"
ONTOLOGY_FETCHER_DISPATCHER = "articles"
ONTOLOGY_DISPATCHER_SUMMARIZER = "summarize"
ONTOLOGY_DISPATCHER_JUDGE = "register-judgement"
ONTOLOGY_SUMMARIZER_JUDGE = "summaries-judge-it"
ONTOLOGY_JUDGE_CHATBOT = "result"
